version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: simpleCrudDb
    volumes:
      - crudData:/var/lib/postgresql/data
volumes:
  crudData: